/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoservismaric.dialog;

import autoservismaric.forms.HomeForm1;
import com.toedter.calendar.JDateChooser;
import data.dto.ZaposleniDTO;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import poslovnalogika.RadniNalogLogika;

/**
 *
 * @author DulleX
 */
public class DodajRadniNalogDialog extends javax.swing.JDialog {

    private int idVozila;
    public RadniNalogLogika radniNalogLogika = new RadniNalogLogika();
    HomeForm1 forma;
    HomeForm1 formaRadniNalog;

    /**
     * Creates new form DodajRadniNalogDialog
     */
    public DodajRadniNalogDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cbPlaceno.setVisible(false);
    }

    public DodajRadniNalogDialog(java.awt.Frame parent, boolean modal, int idVozila, boolean flag) {
        super(parent, modal);
        initComponents();
        this.idVozila = idVozila;
        this.formaRadniNalog = formaRadniNalog;
        cbPlaceno.setVisible(false);
        if(flag)
            this.setTitle("Kreiranje ranog naloga 2/2");
        radniNalogLogika.inicijalizacijaDodajRadniNalog(this);
    }

    public DodajRadniNalogDialog(java.awt.Frame parent, boolean modal, int idVozila, boolean flag, HomeForm1 forma) {
        super(parent, modal);
        initComponents();
        this.idVozila = idVozila;
        cbPlaceno.setVisible(false);
        this.forma = forma;
        if(flag)
            this.setTitle("Kreiranje ranog naloga 2/2");
        radniNalogLogika.inicijalizacijaDodajRadniNalog(this);
    }

    public HomeForm1 getForma() {
        return forma;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOsnovni = new javax.swing.JPanel();
        pnlPodosnovni = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        txtIdVozila = new javax.swing.JTextField();
        lblIdVozila = new javax.swing.JLabel();
        lblOtvaranje = new javax.swing.JLabel();
        lblZatvaranje = new javax.swing.JLabel();
        txtTroskovi = new javax.swing.JTextField();
        lblTroskovi = new javax.swing.JLabel();
        lblKilometraza = new javax.swing.JLabel();
        txtKilometraza = new javax.swing.JTextField();
        lblZavrsavanje = new javax.swing.JLabel();
        lblCijenaUsluge = new javax.swing.JLabel();
        txtCijena = new javax.swing.JTextField();
        cbPlaceno = new javax.swing.JCheckBox();
        spnlProblem = new javax.swing.JScrollPane();
        taProblem = new javax.swing.JTextArea();
        lblOpisProblema = new javax.swing.JLabel();
        datumOtvaranjaNaloga = new com.toedter.calendar.JDateChooser();
        datumZatvaranjaNaloga = new com.toedter.calendar.JDateChooser();
        potrebnoZavrsitiDo = new com.toedter.calendar.JDateChooser();
        btnKreirajNalog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnUkloniDio = new javax.swing.JButton();
        txtCijenaDijela = new javax.swing.JTextField();
        lblIzabraniDijelovi = new javax.swing.JLabel();
        pnlDijelovi = new javax.swing.JScrollPane();
        tblDijelovi = new javax.swing.JTable();
        spinnerKolicina = new javax.swing.JSpinner();
        lblListaDijelova = new javax.swing.JLabel();
        btnDodajDio = new javax.swing.JButton();
        lblCijenaDijela = new javax.swing.JLabel();
        pnlIzabraniDijelovi = new javax.swing.JScrollPane();
        tblIzabraniDijelovi = new javax.swing.JTable();
        lblKolicina = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUlogaRadnika = new javax.swing.JLabel();
        btnRazduzi = new javax.swing.JButton();
        lblZaduzeni = new javax.swing.JLabel();
        btnZaduzi = new javax.swing.JButton();
        spnlSviRadnici = new javax.swing.JScrollPane();
        listaZaposleni = new javax.swing.JList<>();
        spnlUlogaRadnika = new javax.swing.JScrollPane();
        taUlogaRadnika = new javax.swing.JTextArea();
        lblSviRadnici = new javax.swing.JLabel();
        spnlIzabrani = new javax.swing.JScrollPane();
        listaZaposleniZaduzeni = new javax.swing.JList<>();
        brnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novi radni nalog");
        setResizable(false);

        pnlOsnovni.setBackground(new java.awt.Color(102, 153, 255));

        pnlPodosnovni.setBackground(new java.awt.Color(102, 153, 255));
        pnlPodosnovni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNaslov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNaslov.setForeground(new java.awt.Color(255, 255, 255));
        lblNaslov.setText("Novi radni nalog:");

        lblIdVozila.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdVozila.setForeground(new java.awt.Color(255, 255, 255));
        lblIdVozila.setText("Id vozila:");

        lblOtvaranje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOtvaranje.setForeground(new java.awt.Color(255, 255, 255));
        lblOtvaranje.setText("Datum otvaranja naloga:");

        lblZatvaranje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblZatvaranje.setForeground(new java.awt.Color(255, 255, 255));
        lblZatvaranje.setText("Datum završetka:");

        lblTroskovi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTroskovi.setForeground(new java.awt.Color(255, 255, 255));
        lblTroskovi.setText("Troškovi(KM):");

        lblKilometraza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKilometraza.setForeground(new java.awt.Color(255, 255, 255));
        lblKilometraza.setText("Kilometraža(km):");

        lblZavrsavanje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblZavrsavanje.setForeground(new java.awt.Color(255, 255, 255));
        lblZavrsavanje.setText("Potrebno završiti do:");

        lblCijenaUsluge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCijenaUsluge.setForeground(new java.awt.Color(255, 255, 255));
        lblCijenaUsluge.setText("Cijena usluge(KM):");

        cbPlaceno.setBackground(new java.awt.Color(102, 153, 255));
        cbPlaceno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPlaceno.setForeground(new java.awt.Color(240, 240, 240));
        cbPlaceno.setText("Plaćeno");

        taProblem.setColumns(20);
        taProblem.setRows(5);
        taProblem.setWrapStyleWord(true);
        spnlProblem.setViewportView(taProblem);

        lblOpisProblema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpisProblema.setForeground(new java.awt.Color(255, 255, 255));
        lblOpisProblema.setText("Opis problema:");

        btnKreirajNalog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKreirajNalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/add-documents.png"))); // NOI18N
        btnKreirajNalog.setText("Kreiraj nalog");
        btnKreirajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajNalogActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnUkloniDio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUkloniDio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/eraser.png"))); // NOI18N
        btnUkloniDio.setText("Ukloni dio");
        btnUkloniDio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniDioActionPerformed(evt);
            }
        });

        txtCijenaDijela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblIzabraniDijelovi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIzabraniDijelovi.setForeground(new java.awt.Color(255, 255, 255));
        lblIzabraniDijelovi.setText("Izabrani dijelovi:");

        tblDijelovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        pnlDijelovi.setViewportView(tblDijelovi);

        spinnerKolicina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblListaDijelova.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblListaDijelova.setForeground(new java.awt.Color(240, 240, 240));
        lblListaDijelova.setText("Lista dijelova:");

        btnDodajDio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDodajDio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/add (1).png"))); // NOI18N
        btnDodajDio.setText("Dodaj");
        btnDodajDio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDioActionPerformed(evt);
            }
        });

        lblCijenaDijela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCijenaDijela.setForeground(new java.awt.Color(255, 255, 255));
        lblCijenaDijela.setText("Cijena dijela:");

        tblIzabraniDijelovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv", "Šifra", "Količina", "Cijena"
            }
        ));
        pnlIzabraniDijelovi.setViewportView(tblIzabraniDijelovi);

        lblKolicina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKolicina.setForeground(new java.awt.Color(255, 255, 255));
        lblKolicina.setText("Količina:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblCijenaDijela)
                        .addGap(18, 18, 18)
                        .addComponent(txtCijenaDijela, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKolicina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajDio))
                    .addComponent(lblListaDijelova)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlIzabraniDijelovi, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUkloniDio))
                    .addComponent(lblIzabraniDijelovi)
                    .addComponent(pnlDijelovi, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaDijelova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDijelovi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajDio)
                    .addComponent(lblKolicina)
                    .addComponent(lblCijenaDijela)
                    .addComponent(txtCijenaDijela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIzabraniDijelovi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlIzabraniDijelovi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUkloniDio))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUlogaRadnika.setForeground(new java.awt.Color(255, 255, 255));
        lblUlogaRadnika.setText("Uloga radnika:");

        btnRazduzi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRazduzi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/fast-backward-double-left-arrow-symbol.png"))); // NOI18N
        btnRazduzi.setText("Razduži radnika");
        btnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazduziActionPerformed(evt);
            }
        });

        lblZaduzeni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblZaduzeni.setForeground(new java.awt.Color(240, 240, 240));
        lblZaduzeni.setText("Zaduženi radnici:");

        btnZaduzi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnZaduzi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/fast-forward.png"))); // NOI18N
        btnZaduzi.setText("Zaduži radnika");
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        listaZaposleni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaZaposleniValueChanged(evt);
            }
        });
        spnlSviRadnici.setViewportView(listaZaposleni);

        taUlogaRadnika.setEditable(false);
        taUlogaRadnika.setBackground(new java.awt.Color(204, 204, 204));
        taUlogaRadnika.setColumns(20);
        taUlogaRadnika.setLineWrap(true);
        taUlogaRadnika.setRows(4);
        taUlogaRadnika.setWrapStyleWord(true);
        spnlUlogaRadnika.setViewportView(taUlogaRadnika);

        lblSviRadnici.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSviRadnici.setForeground(new java.awt.Color(255, 255, 255));
        lblSviRadnici.setText("Svi radnici");

        listaZaposleniZaduzeni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaZaposleniZaduzeniValueChanged(evt);
            }
        });
        spnlIzabrani.setViewportView(listaZaposleniZaduzeni);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSviRadnici)
                    .addComponent(spnlSviRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUlogaRadnika)
                    .addComponent(spnlUlogaRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaduzi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRazduzi))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZaduzeni)
                    .addComponent(spnlIzabrani, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZaduzeni)
                    .addComponent(lblSviRadnici))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnlIzabrani)
                            .addComponent(spnlSviRadnici))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnZaduzi)
                        .addGap(4, 4, 4)
                        .addComponent(lblUlogaRadnika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnlUlogaRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRazduzi)))
                .addContainerGap())
        );

        brnOdustani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brnOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/cancel (1).png"))); // NOI18N
        brnOdustani.setText("Odustani");
        brnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPodosnovniLayout = new javax.swing.GroupLayout(pnlPodosnovni);
        pnlPodosnovni.setLayout(pnlPodosnovniLayout);
        pnlPodosnovniLayout.setHorizontalGroup(
            pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPodosnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNaslov)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPodosnovniLayout.createSequentialGroup()
                                .addComponent(brnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKreirajNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOpisProblema)
                            .addComponent(spnlProblem)
                            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdVozila)
                                    .addComponent(lblOtvaranje)
                                    .addComponent(lblZatvaranje)
                                    .addComponent(lblTroskovi)
                                    .addComponent(lblKilometraza)
                                    .addComponent(lblZavrsavanje)
                                    .addComponent(lblCijenaUsluge))
                                .addGap(29, 29, 29)
                                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPlaceno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdVozila)
                                    .addComponent(txtTroskovi)
                                    .addComponent(txtKilometraza)
                                    .addComponent(txtCijena)
                                    .addComponent(datumOtvaranjaNaloga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(datumZatvaranjaNaloga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(potrebnoZavrsitiDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(37, 37, 37)
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlPodosnovniLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCijenaUsluge, lblIdVozila, lblKilometraza, lblOtvaranje, lblTroskovi, lblZatvaranje, lblZavrsavanje});

        pnlPodosnovniLayout.setVerticalGroup(
            pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addComponent(lblNaslov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdVozila))
                        .addGap(7, 7, 7)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                .addComponent(lblOtvaranje)
                                .addGap(12, 12, 12)
                                .addComponent(lblZatvaranje))
                            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                .addComponent(datumOtvaranjaNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(datumZatvaranjaNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTroskovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTroskovi))
                        .addGap(7, 7, 7)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKilometraza)
                            .addComponent(txtKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(potrebnoZavrsitiDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZavrsavanje))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCijenaUsluge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPlaceno)
                        .addGap(67, 67, 67)
                        .addComponent(lblOpisProblema))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addComponent(spnlProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKreirajNalog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(brnOdustani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        pnlPodosnovniLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCijenaUsluge, lblIdVozila, lblKilometraza, lblOtvaranje, lblTroskovi, lblZatvaranje, lblZavrsavanje});

        pnlPodosnovniLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {brnOdustani, btnKreirajNalog});

        javax.swing.GroupLayout pnlOsnovniLayout = new javax.swing.GroupLayout(pnlOsnovni);
        pnlOsnovni.setLayout(pnlOsnovniLayout);
        pnlOsnovniLayout.setHorizontalGroup(
            pnlOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOsnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPodosnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOsnovniLayout.setVerticalGroup(
            pnlOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOsnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPodosnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOsnovni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOsnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajNalogActionPerformed
        radniNalogLogika.kreirajNalog(this);
    }//GEN-LAST:event_btnKreirajNalogActionPerformed

    private void btnDodajDioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDioActionPerformed
        radniNalogLogika.dodajDio(this);
    }//GEN-LAST:event_btnDodajDioActionPerformed

    private void btnUkloniDioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniDioActionPerformed
        radniNalogLogika.ukloniDio(this);
    }//GEN-LAST:event_btnUkloniDioActionPerformed

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed
        int brojReda = listaZaposleni.getSelectedIndex();

        if (brojReda < 0) {
            JOptionPane.showMessageDialog(rootPane, "Morate odabrati zaposlenog iz liste svih radnika!", "Greška", JOptionPane.OK_OPTION);
            return;
        }

        ZaposleniDTO red = listaZaposleni.getSelectedValue();
        red.setUlogaRadnika(taUlogaRadnika.getText());
        ((DefaultListModel<ZaposleniDTO>) listaZaposleni.getModel()).removeElementAt(brojReda);
        DefaultListModel<ZaposleniDTO> mod = (DefaultListModel<ZaposleniDTO>) listaZaposleniZaduzeni.getModel();
        mod.addElement(red);
        taUlogaRadnika.setText("");
    }//GEN-LAST:event_btnZaduziActionPerformed

    private void btnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazduziActionPerformed
        int brojReda = listaZaposleniZaduzeni.getSelectedIndex();

        if (brojReda < 0) {
            JOptionPane.showMessageDialog(rootPane, "Morate odabrati zaposlenog iz liste zaduženih radnika!", "Greška", JOptionPane.OK_OPTION);
            return;
        }

        ZaposleniDTO red = listaZaposleniZaduzeni.getSelectedValue();
        ((DefaultListModel<ZaposleniDTO>) listaZaposleniZaduzeni.getModel()).removeElementAt(brojReda);
        DefaultListModel<ZaposleniDTO> mod = (DefaultListModel<ZaposleniDTO>) listaZaposleni.getModel();
        mod.addElement(red);
    }//GEN-LAST:event_btnRazduziActionPerformed

    private void listaZaposleniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaZaposleniValueChanged
        if (listaZaposleni.getSelectedIndex() >= 0) {
            taUlogaRadnika.setEditable(true);
            taUlogaRadnika.setBackground(Color.WHITE);
        } else {
            taUlogaRadnika.setEditable(false);
            taUlogaRadnika.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_listaZaposleniValueChanged

    private void listaZaposleniZaduzeniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaZaposleniZaduzeniValueChanged
    }//GEN-LAST:event_listaZaposleniZaduzeniValueChanged

    private void brnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_brnOdustaniActionPerformed

    public int getIdVozila() {
        return idVozila;
    }

    public HomeForm1 getFormaRadniNalog() {
        return formaRadniNalog;
    }

    public RadniNalogLogika getRadniNalogLogika() {
        return radniNalogLogika;
    }

    public JLabel getZaduzeni() {
        return lblZaduzeni;
    }

    public JButton getBtnDodajDio() {
        return btnDodajDio;
    }

    public JButton getBtnKreirajNalog() {
        return btnKreirajNalog;
    }

    public JButton getBtnRazduzi() {
        return btnRazduzi;
    }

    public JButton getBtnUkloniDio() {
        return btnUkloniDio;
    }

    public JButton getBtnZaduzi() {
        return btnZaduzi;
    }

    public JCheckBox getCbPlaceno() {
        return cbPlaceno;
    }

    public JDateChooser getDatumOtvaranjaNaloga() {
        return datumOtvaranjaNaloga;
    }

    public JDateChooser getDatumZatvaranjaNaloga() {
        return datumZatvaranjaNaloga;
    }

    public JPanel getjPanel1() {
        return pnlOsnovni;
    }

    public JPanel getjPanel2() {
        return pnlPodosnovni;
    }

    public JScrollPane getjScrollPane1() {
        return spnlProblem;
    }

    public JScrollPane getjScrollPane2() {
        return spnlIzabrani;
    }

    public JScrollPane getjScrollPane3() {
        return spnlSviRadnici;
    }

    public JScrollPane getjScrollPane4() {
        return pnlIzabraniDijelovi;
    }

    public JScrollPane getjScrollPane5() {
        return pnlDijelovi;
    }

    public JScrollPane getjScrollPane6() {
        return spnlUlogaRadnika;
    }

    public JList<ZaposleniDTO> getListaZaposleni() {
        return listaZaposleni;
    }

    public JList<ZaposleniDTO> getListaZaposleniZaduzeni() {
        return listaZaposleniZaduzeni;
    }

    public JDateChooser getPotrebnoZavrsitiDo() {
        return potrebnoZavrsitiDo;
    }

    public JSpinner getSpinnerKolicina() {
        return spinnerKolicina;
    }

    public JTextArea getTaProblem() {
        return taProblem;
    }

    public JTextArea getTaUlogaRadnika() {
        return taUlogaRadnika;
    }

    public JTable getTabelaDijelovi() {
        return tblDijelovi;
    }

    public JTable getTabelaIzabraniDijelovi() {
        return tblIzabraniDijelovi;
    }

    public JTextField getTfCijena() {
        return txtCijena;
    }

    public JTextField getTfCijenaDijela() {
        return txtCijenaDijela;
    }

    public JTextField getTfIdVozila() {
        return txtIdVozila;
    }

    public JTextField getTfKilometraza() {
        return txtKilometraza;
    }

    public JTextField getTfTroskovi() {
        return txtTroskovi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DodajRadniNalogDialog dialog = new DodajRadniNalogDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnOdustani;
    private javax.swing.JButton btnDodajDio;
    private javax.swing.JButton btnKreirajNalog;
    private javax.swing.JButton btnRazduzi;
    private javax.swing.JButton btnUkloniDio;
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JCheckBox cbPlaceno;
    private com.toedter.calendar.JDateChooser datumOtvaranjaNaloga;
    private com.toedter.calendar.JDateChooser datumZatvaranjaNaloga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCijenaDijela;
    private javax.swing.JLabel lblCijenaUsluge;
    private javax.swing.JLabel lblIdVozila;
    private javax.swing.JLabel lblIzabraniDijelovi;
    private javax.swing.JLabel lblKilometraza;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblListaDijelova;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblOpisProblema;
    private javax.swing.JLabel lblOtvaranje;
    private javax.swing.JLabel lblSviRadnici;
    private javax.swing.JLabel lblTroskovi;
    private javax.swing.JLabel lblUlogaRadnika;
    private javax.swing.JLabel lblZaduzeni;
    private javax.swing.JLabel lblZatvaranje;
    private javax.swing.JLabel lblZavrsavanje;
    private javax.swing.JList<ZaposleniDTO> listaZaposleni;
    private javax.swing.JList<ZaposleniDTO> listaZaposleniZaduzeni;
    private javax.swing.JScrollPane pnlDijelovi;
    private javax.swing.JScrollPane pnlIzabraniDijelovi;
    private javax.swing.JPanel pnlOsnovni;
    private javax.swing.JPanel pnlPodosnovni;
    private com.toedter.calendar.JDateChooser potrebnoZavrsitiDo;
    private javax.swing.JSpinner spinnerKolicina;
    private javax.swing.JScrollPane spnlIzabrani;
    private javax.swing.JScrollPane spnlProblem;
    private javax.swing.JScrollPane spnlSviRadnici;
    private javax.swing.JScrollPane spnlUlogaRadnika;
    private javax.swing.JTextArea taProblem;
    private javax.swing.JTextArea taUlogaRadnika;
    private javax.swing.JTable tblDijelovi;
    private javax.swing.JTable tblIzabraniDijelovi;
    private javax.swing.JTextField txtCijena;
    private javax.swing.JTextField txtCijenaDijela;
    private javax.swing.JTextField txtIdVozila;
    private javax.swing.JTextField txtKilometraza;
    private javax.swing.JTextField txtTroskovi;
    // End of variables declaration//GEN-END:variables
}
