/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoservismaric.dialog;

import autoservismaric.forms.HomeForm1;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import poslovnalogika.MarkaIModelUcitavanje;
import poslovnalogika.VoziloKupacMeniLogika;

/**
 *
 * @author DulleX
 */
public class IzaberiVoziloDialog extends javax.swing.JDialog {

    /**
     * Creates new form IzaberiVoziloDialog
     */
    
    private VoziloKupacMeniLogika voziloKupacMeniLogika = new VoziloKupacMeniLogika();
    ButtonGroup bGTraziVozilo;
    HomeForm1 forma;
    int idVozila=-1;
    
    public IzaberiVoziloDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bGTraziVozilo = new ButtonGroup();
        bGTraziVozilo.add(rbPravnoLiceVozilo);
        bGTraziVozilo.add(rbPrivatnoLiceVozilo);
        btnPrikaziSvaVozila.doClick();
        tableVozila.getTableHeader().setReorderingAllowed(false);
        tableVozila.setDefaultEditor(Object.class, null);

        tableVozila.setAutoCreateRowSorter(true);
        tableVozila.setAutoCreateRowSorter(true);
        
        tableVozila.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (tableVozila.getSelectedRow() > -1) {
                    idVozila = Integer.parseInt(tableVozila.getValueAt(tableVozila.getSelectedRow(), 0).toString());
                    btnKreirajRadniNalog.setEnabled(true);
                }
                else{
                    idVozila = -1;
                    btnKreirajRadniNalog.setEnabled(false);
                }
            }
        });
        autoSuggestorMarkaIModelVozila();
    }
    
    public IzaberiVoziloDialog(java.awt.Frame parent, boolean modal, HomeForm1 forma) {
        super(parent, modal);
        initComponents();
        this.forma = forma;
        bGTraziVozilo = new ButtonGroup();
        bGTraziVozilo.add(rbPravnoLiceVozilo);
        bGTraziVozilo.add(rbPrivatnoLiceVozilo);
        btnPrikaziSvaVozila.doClick();
        tableVozila.getTableHeader().setReorderingAllowed(false);
        tableVozila.setDefaultEditor(Object.class, null);

        tableVozila.setAutoCreateRowSorter(true);
        tableVozila.setAutoCreateRowSorter(true);
        
        tableVozila.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (tableVozila.getSelectedRow() > -1) {
                    idVozila = Integer.parseInt(tableVozila.getValueAt(tableVozila.getSelectedRow(), 0).toString());
                    btnKreirajRadniNalog.setEnabled(true);
                }
                else{
                    idVozila = -1;
                    btnKreirajRadniNalog.setEnabled(false);
                }
            }
        });
        
       autoSuggestorMarkaIModelVozila();
    }

    private void autoSuggestorMarkaIModelVozila(){
         //auto suggestor
        ArrayList<String> marke=MarkaIModelUcitavanje.ucitajSveMarke();
        cbMarkaVozila.addItem("");
        for(int i=0;i<marke.size();i++){
            cbMarkaVozila.addItem(marke.get(i));
        }
        AutoCompleteDecorator.decorate(cbMarkaVozila);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOsnovni = new javax.swing.JPanel();
        panelTabela = new javax.swing.JScrollPane();
        tableVozila = new javax.swing.JTable();
        lblNaslov = new javax.swing.JLabel();
        btnKreirajRadniNalog = new javax.swing.JButton();
        panelPretraga = new javax.swing.JPanel();
        cbSvi = new javax.swing.JCheckBox();
        lblMarka = new javax.swing.JLabel();
        tfNazivVozilo = new javax.swing.JTextField();
        lblIme = new javax.swing.JLabel();
        tfPrezimeVozilo = new javax.swing.JTextField();
        lblPrezime = new javax.swing.JLabel();
        tfImeVozilo = new javax.swing.JTextField();
        btnPrikaziSvaVozila = new javax.swing.JButton();
        btnPronadjiVozilo = new javax.swing.JButton();
        lblVlasnik = new javax.swing.JLabel();
        lblRegistracija = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        tfRegistracijaTrazi = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        tfGodisteTrazi = new javax.swing.JTextField();
        rbPravnoLiceVozilo = new javax.swing.JRadioButton();
        btnPonistiSve = new javax.swing.JButton();
        rbPrivatnoLiceVozilo = new javax.swing.JRadioButton();
        lblGodiste = new javax.swing.JLabel();
        cbMarkaVozila = new javax.swing.JComboBox<>();
        cbModelVozila = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiranje radnog naloga(1/2)");

        panelOsnovni.setBackground(new java.awt.Color(102, 153, 255));

        tableVozila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        panelTabela.setViewportView(tableVozila);

        lblNaslov.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNaslov.setForeground(new java.awt.Color(255, 255, 255));
        lblNaslov.setText("Izbor vozila za koji se kreira radni nalog:");

        btnKreirajRadniNalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKreirajRadniNalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/add-documents.png"))); // NOI18N
        btnKreirajRadniNalog.setText("Kreiraj radni nalog");
        btnKreirajRadniNalog.setEnabled(false);
        btnKreirajRadniNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajRadniNalogActionPerformed(evt);
            }
        });

        panelPretraga.setBackground(new java.awt.Color(102, 153, 255));
        panelPretraga.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbSvi.setBackground(new java.awt.Color(102, 153, 255));
        cbSvi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSvi.setForeground(new java.awt.Color(240, 240, 240));
        cbSvi.setText("Svi");
        cbSvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSviActionPerformed(evt);
            }
        });

        lblMarka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarka.setForeground(new java.awt.Color(255, 255, 255));
        lblMarka.setText("Marka:");

        tfNazivVozilo.setEditable(false);
        tfNazivVozilo.setBackground(java.awt.Color.gray);

        lblIme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIme.setForeground(new java.awt.Color(255, 255, 255));
        lblIme.setText("Ime:");

        lblPrezime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPrezime.setForeground(new java.awt.Color(255, 255, 255));
        lblPrezime.setText("Prezime:");

        btnPrikaziSvaVozila.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrikaziSvaVozila.setText("Prikaži sve");
        btnPrikaziSvaVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSvaVozilaActionPerformed(evt);
            }
        });

        btnPronadjiVozilo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPronadjiVozilo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/search.png"))); // NOI18N
        btnPronadjiVozilo.setText("Traži");
        btnPronadjiVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiVoziloActionPerformed(evt);
            }
        });

        lblVlasnik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVlasnik.setForeground(new java.awt.Color(255, 255, 255));
        lblVlasnik.setText("Vlasnik:");

        lblRegistracija.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistracija.setText("Registracija:");

        lblNaziv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNaziv.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv.setText("Naziv:");

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("Model:");

        rbPravnoLiceVozilo.setBackground(new java.awt.Color(102, 153, 255));
        rbPravnoLiceVozilo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPravnoLiceVozilo.setForeground(new java.awt.Color(255, 255, 255));
        rbPravnoLiceVozilo.setText("Pravno lice");
        rbPravnoLiceVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPravnoLiceVoziloActionPerformed(evt);
            }
        });

        btnPonistiSve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPonistiSve.setText("Poništi unose");
        btnPonistiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiSveActionPerformed(evt);
            }
        });

        rbPrivatnoLiceVozilo.setBackground(new java.awt.Color(102, 153, 255));
        rbPrivatnoLiceVozilo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPrivatnoLiceVozilo.setForeground(new java.awt.Color(255, 255, 255));
        rbPrivatnoLiceVozilo.setSelected(true);
        rbPrivatnoLiceVozilo.setText("Privatno lice");
        rbPrivatnoLiceVozilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrivatnoLiceVoziloActionPerformed(evt);
            }
        });

        lblGodiste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGodiste.setForeground(new java.awt.Color(255, 255, 255));
        lblGodiste.setText("Godište:");

        cbMarkaVozila.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMarkaVozilaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelPretragaLayout = new javax.swing.GroupLayout(panelPretraga);
        panelPretraga.setLayout(panelPretragaLayout);
        panelPretragaLayout.setHorizontalGroup(
            panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPretragaLayout.createSequentialGroup()
                        .addComponent(btnPrikaziSvaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPonistiSve))
                    .addGroup(panelPretragaLayout.createSequentialGroup()
                        .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistracija)
                            .addComponent(lblMarka)
                            .addComponent(lblModel)
                            .addComponent(lblGodiste))
                        .addGap(18, 18, 18)
                        .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRegistracijaTrazi)
                            .addComponent(tfGodisteTrazi)
                            .addComponent(cbMarkaVozila, 0, 192, Short.MAX_VALUE)
                            .addComponent(cbModelVozila, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(83, 83, 83)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPretragaLayout.createSequentialGroup()
                            .addComponent(lblNaziv)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNazivVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                            .addComponent(lblIme)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfImeVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                            .addComponent(lblPrezime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPrezimeVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPretragaLayout.createSequentialGroup()
                            .addComponent(lblVlasnik)
                            .addGap(25, 25, 25)
                            .addComponent(rbPrivatnoLiceVozilo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbPravnoLiceVozilo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbSvi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPronadjiVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        panelPretragaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPonistiSve, btnPrikaziSvaVozila});

        panelPretragaLayout.setVerticalGroup(
            panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPretragaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRegistracijaTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistracija)
                    .addComponent(lblVlasnik)
                    .addComponent(rbPrivatnoLiceVozilo)
                    .addComponent(rbPravnoLiceVozilo)
                    .addComponent(cbSvi))
                .addGap(11, 11, 11)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGodisteTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGodiste)
                    .addComponent(lblPrezime)
                    .addComponent(tfPrezimeVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarka)
                    .addComponent(lblIme)
                    .addComponent(tfImeVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMarkaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNazivVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNaziv)
                    .addComponent(lblModel)
                    .addComponent(cbModelVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPretragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPronadjiVozilo)
                    .addComponent(btnPonistiSve, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziSvaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPretragaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPonistiSve, btnPrikaziSvaVozila});

        javax.swing.GroupLayout panelOsnovniLayout = new javax.swing.GroupLayout(panelOsnovni);
        panelOsnovni.setLayout(panelOsnovniLayout);
        panelOsnovniLayout.setHorizontalGroup(
            panelOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOsnovniLayout.createSequentialGroup()
                .addGroup(panelOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOsnovniLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKreirajRadniNalog))
                    .addGroup(panelOsnovniLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOsnovniLayout.createSequentialGroup()
                                .addComponent(lblNaslov)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(panelTabela, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelOsnovniLayout.setVerticalGroup(
            panelOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOsnovniLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNaslov)
                .addGap(18, 18, 18)
                .addComponent(panelPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajRadniNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOsnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOsnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajRadniNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajRadniNalogActionPerformed
        if(idVozila > -1){
            new DodajRadniNalogDialog(new JFrame(), true, idVozila, true, forma).setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(new JFrame(), "Morate odabrati vozilo iz tabele!", "Greška!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnKreirajRadniNalogActionPerformed

    private void btnPronadjiVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiVoziloActionPerformed
        //izbrisiPopupZaVlasnike();
        //ucitajPopupZaVozila();
        voziloKupacMeniLogika.pronadjiVozilo(this);
    }//GEN-LAST:event_btnPronadjiVoziloActionPerformed

    private void btnPonistiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiSveActionPerformed
        tfRegistracijaTrazi.setText("");
        tfGodisteTrazi.setText("");
        cbMarkaVozila.setSelectedIndex(0);
        tfPrezimeVozilo.setText("");
        tfImeVozilo.setText("");
        tfNazivVozilo.setText("");
        rbPrivatnoLiceVozilo.setSelected(true);
        rbPravnoLiceVozilo.setSelected(false);
        tfNazivVozilo.setEditable(false);
        tfNazivVozilo.setBackground(Color.gray);
        tfImeVozilo.setBackground(Color.white);
        tfPrezimeVozilo.setBackground(Color.white);
        tfImeVozilo.setEditable(true);
        tfPrezimeVozilo.setEditable(true);
    }//GEN-LAST:event_btnPonistiSveActionPerformed

    private void btnPrikaziSvaVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSvaVozilaActionPerformed
        //izbrisiPopupZaVlasnike();
        //ucitajPopupZaVozila();
        voziloKupacMeniLogika.prikaziSvaVozila(this);
    }//GEN-LAST:event_btnPrikaziSvaVozilaActionPerformed

    private void rbPravnoLiceVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPravnoLiceVoziloActionPerformed
        tfNazivVozilo.setEditable(true);
        tfImeVozilo.setEditable(false);
        tfPrezimeVozilo.setEditable(false);
        tfImeVozilo.setText("");
        tfPrezimeVozilo.setText("");
        tfImeVozilo.setBackground(Color.gray);
        tfPrezimeVozilo.setBackground(Color.gray);
        tfNazivVozilo.setBackground(Color.white);
        rbPrivatnoLiceVozilo.setSelected(false);
        cbSvi.setSelected(false);
    }//GEN-LAST:event_rbPravnoLiceVoziloActionPerformed

    private void rbPrivatnoLiceVoziloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrivatnoLiceVoziloActionPerformed
        cbSvi.setSelected(false);
        tfNazivVozilo.setEditable(false);
        tfNazivVozilo.setText("");
        tfImeVozilo.setEditable(true);
        tfPrezimeVozilo.setEditable(true);
        tfNazivVozilo.setBackground(Color.gray);
        rbPravnoLiceVozilo.setSelected(false);
        tfImeVozilo.setBackground(Color.white);
        tfPrezimeVozilo.setBackground(Color.white);
    }//GEN-LAST:event_rbPrivatnoLiceVoziloActionPerformed

    private void cbSviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSviActionPerformed
        if (cbSvi.isSelected()) {
            bGTraziVozilo.clearSelection();
            tfImeVozilo.setEditable(false);
            tfImeVozilo.setBackground(Color.gray);
            tfImeVozilo.setText("");
            tfPrezimeVozilo.setEditable(false);
            tfPrezimeVozilo.setBackground(Color.gray);
            tfPrezimeVozilo.setText("");
            tfNazivVozilo.setEditable(false);
            tfNazivVozilo.setBackground(Color.gray);
            tfNazivVozilo.setText("");
        } else {
            rbPrivatnoLiceVozilo.setSelected(true);
            rbPravnoLiceVozilo.setSelected(false);
            tfImeVozilo.setEditable(true);
            tfImeVozilo.setText("");
            tfImeVozilo.setBackground(Color.white);
            tfPrezimeVozilo.setEditable(true);
            tfPrezimeVozilo.setText("");
            tfPrezimeVozilo.setBackground(Color.white);
        }
    }//GEN-LAST:event_cbSviActionPerformed

    private void cbMarkaVozilaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMarkaVozilaItemStateChanged
        if (cbMarkaVozila.getSelectedIndex()!=-1 && cbMarkaVozila.getSelectedIndex()!=0) {
            System.out.println(cbMarkaVozila.getSelectedIndex());
            ArrayList<String> model = MarkaIModelUcitavanje.ucitajSveModele(cbMarkaVozila.getSelectedItem().toString());
            cbModelVozila.removeAllItems();
            cbModelVozila.addItem("");
            for (int i = 0; i < model.size(); i++) {
                cbModelVozila.addItem(model.get(i));
            }
        }
    }//GEN-LAST:event_cbMarkaVozilaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzaberiVoziloDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzaberiVoziloDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzaberiVoziloDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzaberiVoziloDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzaberiVoziloDialog dialog = new IzaberiVoziloDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnPonistiSve() {
        return btnPonistiSve;
    }

    public void setBtnPonistiSve(JButton btnPonistiSve) {
        this.btnPonistiSve = btnPonistiSve;
    }

    public JButton getBtnPrikaziSvaVozila() {
        return btnPrikaziSvaVozila;
    }

    public void setBtnPrikaziSvaVozila(JButton btnPrikaziSvaVozila) {
        this.btnPrikaziSvaVozila = btnPrikaziSvaVozila;
    }

    public JButton getBtnPronadjiVozilo() {
        return btnPronadjiVozilo;
    }

    public void setBtnPronadjiVozilo(JButton btnPronadjiVozilo) {
        this.btnPronadjiVozilo = btnPronadjiVozilo;
    }

    public JCheckBox getCbSvi() {
        return cbSvi;
    }

    public void setCbSvi(JCheckBox cbSvi) {
        this.cbSvi = cbSvi;
    }

    public JButton getjButton1() {
        return btnKreirajRadniNalog;
    }

    public void setjButton1(JButton jButton1) {
        this.btnKreirajRadniNalog = jButton1;
    }

    public JLabel getjLabel1() {
        return lblNaslov;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.lblNaslov = jLabel1;
    }

    public JLabel getjLabel105() {
        return lblRegistracija;
    }

    public void setjLabel105(JLabel jLabel105) {
        this.lblRegistracija = jLabel105;
    }

    public JLabel getjLabel106() {
        return lblGodiste;
    }

    public void setjLabel106(JLabel jLabel106) {
        this.lblGodiste = jLabel106;
    }

    public JLabel getjLabel107() {
        return lblModel;
    }

    public void setjLabel107(JLabel jLabel107) {
        this.lblModel = jLabel107;
    }

    public JLabel getjLabel108() {
        return lblPrezime;
    }

    public void setjLabel108(JLabel jLabel108) {
        this.lblPrezime = jLabel108;
    }

    public JLabel getjLabel22() {
        return lblIme;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.lblIme = jLabel22;
    }

    public JLabel getjLabel23() {
        return lblVlasnik;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.lblVlasnik = jLabel23;
    }

    public JLabel getjLabel28() {
        return lblMarka;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.lblMarka = jLabel28;
    }

    public JLabel getjLabel29() {
        return lblNaziv;
    }

    public void setjLabel29(JLabel jLabel29) {
        this.lblNaziv = jLabel29;
    }

    public JPanel getjPanel1() {
        return panelOsnovni;
    }

    

    public JScrollPane getjScrollPane1() {
        return panelTabela;
    }


    public JRadioButton getRbPravnoLiceVozilo() {
        return rbPravnoLiceVozilo;
    }

    public void setRbPravnoLiceVozilo(JRadioButton rbPravnoLiceVozilo) {
        this.rbPravnoLiceVozilo = rbPravnoLiceVozilo;
    }

    public JRadioButton getRbPrivatnoLiceVozilo() {
        return rbPrivatnoLiceVozilo;
    }

 

    public JTextField getTfGodisteTrazi() {
        return tfGodisteTrazi;
    }

    public JTable getTableVozila() {
        return tableVozila;
    }

    public void setTfGodisteTrazi(JTextField tfGodisteTrazi) {
        this.tfGodisteTrazi = tfGodisteTrazi;
    }

    public JTextField getTfImeVozilo() {
        return tfImeVozilo;
    }

    public void setTfImeVozilo(JTextField tfImeVozilo) {
        this.tfImeVozilo = tfImeVozilo;
    }

    public JComboBox<String> getCbMarkaVozila() {
        return cbMarkaVozila;
    }

    public void setCbMarkaVozila(JComboBox<String> cbMarkaVozila) {
        this.cbMarkaVozila = cbMarkaVozila;
    }

    public JComboBox<String> getCbModelVozila() {
        return cbModelVozila;
    }

    public void setCbModelVozila(JComboBox<String> cbModelVozila) {
        this.cbModelVozila = cbModelVozila;
    }

    

    public JTextField getTfNazivVozilo() {
        return tfNazivVozilo;
    }

    public void setTfNazivVozilo(JTextField tfNazivVozilo) {
        this.tfNazivVozilo = tfNazivVozilo;
    }

    public JTextField getTfPrezimeVozilo() {
        return tfPrezimeVozilo;
    }

    public void setTfPrezimeVozilo(JTextField tfPrezimeVozilo) {
        this.tfPrezimeVozilo = tfPrezimeVozilo;
    }

    public JTextField getTfRegistracijaTrazi() {
        return tfRegistracijaTrazi;
    }

    public void setTfRegistracijaTrazi(JTextField tfRegistracijaTrazi) {
        this.tfRegistracijaTrazi = tfRegistracijaTrazi;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajRadniNalog;
    private javax.swing.JButton btnPonistiSve;
    private javax.swing.JButton btnPrikaziSvaVozila;
    private javax.swing.JButton btnPronadjiVozilo;
    private javax.swing.JComboBox<String> cbMarkaVozila;
    private javax.swing.JComboBox<String> cbModelVozila;
    private javax.swing.JCheckBox cbSvi;
    private javax.swing.JLabel lblGodiste;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblRegistracija;
    private javax.swing.JLabel lblVlasnik;
    private javax.swing.JPanel panelOsnovni;
    private javax.swing.JPanel panelPretraga;
    private javax.swing.JScrollPane panelTabela;
    private javax.swing.JRadioButton rbPravnoLiceVozilo;
    private javax.swing.JRadioButton rbPrivatnoLiceVozilo;
    private javax.swing.JTable tableVozila;
    private javax.swing.JTextField tfGodisteTrazi;
    private javax.swing.JTextField tfImeVozilo;
    private javax.swing.JTextField tfNazivVozilo;
    private javax.swing.JTextField tfPrezimeVozilo;
    private javax.swing.JTextField tfRegistracijaTrazi;
    // End of variables declaration//GEN-END:variables
}
