package autoservismaric.dialog;

import autoservismaric.forms.HomeForm1;
import com.toedter.calendar.JDateChooser;
import data.dto.RadniNalogDTO;
import data.dto.ZaposleniDTO;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import poslovnalogika.RadniNalogLogika;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DulleX
 */
public class IzmijeniRadniNalogDialog extends javax.swing.JDialog {

    /**
     * Creates new form IzmijeniRadniNalogDialog2
     */
    private int idRadnogNaloga;
    private int idVozila;
    private RadniNalogDTO nalog;
    public RadniNalogLogika radniNalogLogika = new RadniNalogLogika();
    private HomeForm1 homeForm;
    
    public IzmijeniRadniNalogDialog(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        cbPlaceno.setVisible(false);
    }

    public IzmijeniRadniNalogDialog(java.awt.Frame parent, boolean modal, int idRadnogNaloga,HomeForm1 homeForm) {
        super(parent, modal);
        initComponents();
        
        this.homeForm=homeForm;
        cbPlaceno.setVisible(false);
        this.idRadnogNaloga = idRadnogNaloga;
        radniNalogLogika.inicijalizujIzmijeniRadniNalog(this,homeForm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOsnovni = new javax.swing.JPanel();
        pnlPodosnovni = new javax.swing.JPanel();
        lblNaslov = new javax.swing.JLabel();
        txtIdVozila = new javax.swing.JTextField();
        lblIdVozila = new javax.swing.JLabel();
        lblOtvaranje = new javax.swing.JLabel();
        lblZavrsetak = new javax.swing.JLabel();
        txtTroskovi = new javax.swing.JTextField();
        lblTroskovi = new javax.swing.JLabel();
        lblKilometraza = new javax.swing.JLabel();
        txtKilometraza = new javax.swing.JTextField();
        lblZavrsiti = new javax.swing.JLabel();
        lblCijena = new javax.swing.JLabel();
        txtCijena = new javax.swing.JTextField();
        cbPlaceno = new javax.swing.JCheckBox();
        spnlProblem = new javax.swing.JScrollPane();
        taProblem = new javax.swing.JTextArea();
        lblOpis = new javax.swing.JLabel();
        datumOtvaranjaNaloga = new com.toedter.calendar.JDateChooser();
        datumZatvaranjaNaloga = new com.toedter.calendar.JDateChooser();
        potrebnoZavrsitiDo = new com.toedter.calendar.JDateChooser();
        btnAzurirajNalog = new javax.swing.JButton();
        pnlPomocni1 = new javax.swing.JPanel();
        lblCijenaDijela = new javax.swing.JLabel();
        lblKolicina = new javax.swing.JLabel();
        spnlIzabraniDijelovi = new javax.swing.JScrollPane();
        tblIzabraniDijelovi = new javax.swing.JTable();
        txtCijenaDijela = new javax.swing.JTextField();
        btnUkloniDio = new javax.swing.JButton();
        lblListaDijelova = new javax.swing.JLabel();
        spinnerKolicina = new javax.swing.JSpinner();
        spnlLista = new javax.swing.JScrollPane();
        tblDijelovi = new javax.swing.JTable();
        lblIzabraniDijelovi = new javax.swing.JLabel();
        btnDodajDio = new javax.swing.JButton();
        pnlPomocni2 = new javax.swing.JPanel();
        lblSviRadnici = new javax.swing.JLabel();
        Zaduzeni = new javax.swing.JLabel();
        btnRazduzi = new javax.swing.JButton();
        spnlRadnici = new javax.swing.JScrollPane();
        listaZaposleni = new javax.swing.JList<>();
        spnlZaduzeni = new javax.swing.JScrollPane();
        listaZaposleniZaduzeni = new javax.swing.JList<>();
        lblUloga = new javax.swing.JLabel();
        spnlUloga = new javax.swing.JScrollPane();
        taUlogaRadnika = new javax.swing.JTextArea();
        btnZaduzi = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmijeni radni nalog");

        pnlOsnovni.setBackground(new java.awt.Color(102, 153, 255));

        pnlPodosnovni.setBackground(new java.awt.Color(102, 153, 255));
        pnlPodosnovni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNaslov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNaslov.setForeground(new java.awt.Color(255, 255, 255));
        lblNaslov.setText("Izmijeni radni nalog:");

        lblIdVozila.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdVozila.setForeground(new java.awt.Color(255, 255, 255));
        lblIdVozila.setText("Id vozila:");

        lblOtvaranje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOtvaranje.setForeground(new java.awt.Color(255, 255, 255));
        lblOtvaranje.setText("Datum otvaranja naloga:");

        lblZavrsetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblZavrsetak.setForeground(new java.awt.Color(255, 255, 255));
        lblZavrsetak.setText("Datum završetka:");

        lblTroskovi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTroskovi.setForeground(new java.awt.Color(255, 255, 255));
        lblTroskovi.setText("Troškovi(KM):");

        lblKilometraza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKilometraza.setForeground(new java.awt.Color(255, 255, 255));
        lblKilometraza.setText("Kilometraža:");

        lblZavrsiti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblZavrsiti.setForeground(new java.awt.Color(255, 255, 255));
        lblZavrsiti.setText("Potrebno završiti do:");

        lblCijena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCijena.setForeground(new java.awt.Color(255, 255, 255));
        lblCijena.setText("Cijena usluge(KM):");

        cbPlaceno.setBackground(new java.awt.Color(102, 153, 255));
        cbPlaceno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPlaceno.setForeground(new java.awt.Color(240, 240, 240));
        cbPlaceno.setText("Plaćeno");

        taProblem.setColumns(20);
        taProblem.setRows(5);
        taProblem.setWrapStyleWord(true);
        spnlProblem.setViewportView(taProblem);

        lblOpis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpis.setForeground(new java.awt.Color(255, 255, 255));
        lblOpis.setText("Opis problema:");

        datumOtvaranjaNaloga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datumOtvaranjaNalogaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                datumOtvaranjaNalogaFocusLost(evt);
            }
        });

        btnAzurirajNalog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAzurirajNalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/add-documents.png"))); // NOI18N
        btnAzurirajNalog.setText("Izmijeni nalog");
        btnAzurirajNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajNalogActionPerformed(evt);
            }
        });

        pnlPomocni1.setBackground(new java.awt.Color(102, 153, 255));
        pnlPomocni1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCijenaDijela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCijenaDijela.setForeground(new java.awt.Color(255, 255, 255));
        lblCijenaDijela.setText("Cijena dijela(KM):");

        lblKolicina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKolicina.setForeground(new java.awt.Color(255, 255, 255));
        lblKolicina.setText("Količina:");

        tblIzabraniDijelovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv", "Šifra", "Količina", "Cijena/kom(KM)"
            }
        ));
        spnlIzabraniDijelovi.setViewportView(tblIzabraniDijelovi);

        txtCijenaDijela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnUkloniDio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUkloniDio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/eraser.png"))); // NOI18N
        btnUkloniDio.setText("Ukloni dio");
        btnUkloniDio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniDioActionPerformed(evt);
            }
        });

        lblListaDijelova.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblListaDijelova.setForeground(new java.awt.Color(240, 240, 240));
        lblListaDijelova.setText("Lista dijelova:");

        spinnerKolicina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblDijelovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        spnlLista.setViewportView(tblDijelovi);

        lblIzabraniDijelovi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIzabraniDijelovi.setForeground(new java.awt.Color(255, 255, 255));
        lblIzabraniDijelovi.setText("Izabrani dijelovi:");

        btnDodajDio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDodajDio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/add (1).png"))); // NOI18N
        btnDodajDio.setText("Dodaj");
        btnDodajDio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPomocni1Layout = new javax.swing.GroupLayout(pnlPomocni1);
        pnlPomocni1.setLayout(pnlPomocni1Layout);
        pnlPomocni1Layout.setHorizontalGroup(
            pnlPomocni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPomocni1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPomocni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPomocni1Layout.createSequentialGroup()
                        .addComponent(lblListaDijelova)
                        .addGap(136, 136, 136)
                        .addComponent(lblCijenaDijela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCijenaDijela, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblKolicina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDodajDio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIzabraniDijelovi)
                    .addComponent(spnlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPomocni1Layout.createSequentialGroup()
                        .addComponent(spnlIzabraniDijelovi, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUkloniDio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPomocni1Layout.setVerticalGroup(
            pnlPomocni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPomocni1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPomocni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListaDijelova)
                    .addComponent(lblCijenaDijela)
                    .addComponent(txtCijenaDijela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKolicina)
                    .addComponent(spinnerKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajDio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnlLista, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPomocni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPomocni1Layout.createSequentialGroup()
                        .addComponent(lblIzabraniDijelovi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnlIzabraniDijelovi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUkloniDio))
                .addContainerGap())
        );

        pnlPomocni2.setBackground(new java.awt.Color(102, 153, 255));
        pnlPomocni2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSviRadnici.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSviRadnici.setForeground(new java.awt.Color(255, 255, 255));
        lblSviRadnici.setText("Svi radnici");

        Zaduzeni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Zaduzeni.setForeground(new java.awt.Color(240, 240, 240));
        Zaduzeni.setText("Zaduženi radnici:");

        btnRazduzi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRazduzi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/fast-backward-double-left-arrow-symbol.png"))); // NOI18N
        btnRazduzi.setText("Razduži radnika");
        btnRazduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazduziActionPerformed(evt);
            }
        });

        listaZaposleni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaZaposleniValueChanged(evt);
            }
        });
        spnlRadnici.setViewportView(listaZaposleni);

        listaZaposleniZaduzeni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaZaposleniZaduzeniValueChanged(evt);
            }
        });
        spnlZaduzeni.setViewportView(listaZaposleniZaduzeni);

        lblUloga.setForeground(new java.awt.Color(255, 255, 255));
        lblUloga.setText("Uloga radnika:");

        taUlogaRadnika.setEditable(false);
        taUlogaRadnika.setBackground(new java.awt.Color(204, 204, 204));
        taUlogaRadnika.setColumns(20);
        taUlogaRadnika.setLineWrap(true);
        taUlogaRadnika.setRows(4);
        taUlogaRadnika.setWrapStyleWord(true);
        spnlUloga.setViewportView(taUlogaRadnika);

        btnZaduzi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnZaduzi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/fast-forward.png"))); // NOI18N
        btnZaduzi.setText("Zaduži radnika");
        btnZaduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPomocni2Layout = new javax.swing.GroupLayout(pnlPomocni2);
        pnlPomocni2.setLayout(pnlPomocni2Layout);
        pnlPomocni2Layout.setHorizontalGroup(
            pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPomocni2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSviRadnici)
                    .addComponent(spnlRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUloga)
                        .addComponent(spnlUloga, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addComponent(btnRazduzi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnZaduzi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPomocni2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(spnlZaduzeni, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlPomocni2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Zaduzeni)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlPomocni2Layout.setVerticalGroup(
            pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPomocni2Layout.createSequentialGroup()
                .addGroup(pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPomocni2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPomocni2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPomocni2Layout.createSequentialGroup()
                                .addComponent(btnZaduzi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUloga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnlUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRazduzi))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPomocni2Layout.createSequentialGroup()
                                .addComponent(Zaduzeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnlZaduzeni, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPomocni2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSviRadnici)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnlRadnici, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnOdustani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/cancel (1).png"))); // NOI18N
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPodosnovniLayout = new javax.swing.GroupLayout(pnlPodosnovni);
        pnlPodosnovni.setLayout(pnlPodosnovniLayout);
        pnlPodosnovniLayout.setHorizontalGroup(
            pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPodosnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNaslov)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                .addComponent(btnOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAzurirajNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOpis)
                            .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spnlProblem)
                                .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                    .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIdVozila)
                                        .addComponent(lblOtvaranje)
                                        .addComponent(lblZavrsetak)
                                        .addComponent(lblTroskovi)
                                        .addComponent(lblKilometraza)
                                        .addComponent(lblZavrsiti)
                                        .addComponent(lblCijena))
                                    .addGap(29, 29, 29)
                                    .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbPlaceno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIdVozila)
                                        .addComponent(txtTroskovi)
                                        .addComponent(txtKilometraza)
                                        .addComponent(txtCijena)
                                        .addComponent(datumOtvaranjaNaloga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(datumZatvaranjaNaloga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(potrebnoZavrsitiDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(37, 37, 37)
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPomocni1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, Short.MAX_VALUE)
                    .addComponent(pnlPomocni2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPodosnovniLayout.setVerticalGroup(
            pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addComponent(lblNaslov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdVozila))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                .addComponent(lblOtvaranje)
                                .addGap(12, 12, 12)
                                .addComponent(lblZavrsetak))
                            .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                                .addComponent(datumOtvaranjaNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datumZatvaranjaNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTroskovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTroskovi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKilometraza)
                            .addComponent(txtKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(potrebnoZavrsitiDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZavrsiti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCijena)
                            .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPlaceno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpis)
                        .addGap(43, 43, 43))
                    .addComponent(pnlPomocni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodosnovniLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spnlProblem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPodosnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAzurirajNalog, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPodosnovniLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlPomocni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout pnlOsnovniLayout = new javax.swing.GroupLayout(pnlOsnovni);
        pnlOsnovni.setLayout(pnlOsnovniLayout);
        pnlOsnovniLayout.setHorizontalGroup(
            pnlOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOsnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPodosnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOsnovniLayout.setVerticalGroup(
            pnlOsnovniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOsnovniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPodosnovni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOsnovni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOsnovni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajDioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDioActionPerformed
        radniNalogLogika.dodajDio(this);
    }//GEN-LAST:event_btnDodajDioActionPerformed

    private void listaZaposleniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaZaposleniValueChanged
        if (listaZaposleni.getSelectedIndex() >= 0) {
            taUlogaRadnika.setEditable(true);
            taUlogaRadnika.setBackground(Color.WHITE);
        } else {
            taUlogaRadnika.setEditable(false);
            taUlogaRadnika.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_listaZaposleniValueChanged

    private void btnRazduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazduziActionPerformed
        int brojReda = listaZaposleniZaduzeni.getSelectedIndex();

        if (brojReda < 0) {
            JOptionPane.showMessageDialog(rootPane, "Morate odabrati zaposlenog iz liste zaduženih radnika!", "Greška", JOptionPane.OK_OPTION);
            return;
        }

        ZaposleniDTO red = listaZaposleniZaduzeni.getSelectedValue();

        ((DefaultListModel<ZaposleniDTO>) listaZaposleniZaduzeni.getModel()).removeElementAt(brojReda);

        DefaultListModel<ZaposleniDTO> mod = (DefaultListModel<ZaposleniDTO>) listaZaposleni.getModel();
        mod.addElement(red);
    }//GEN-LAST:event_btnRazduziActionPerformed

    private void btnAzurirajNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajNalogActionPerformed
        radniNalogLogika.azurirajNalog(this,homeForm);
    }//GEN-LAST:event_btnAzurirajNalogActionPerformed

    private void btnUkloniDioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniDioActionPerformed
        radniNalogLogika.ukloniDio(this);
    }//GEN-LAST:event_btnUkloniDioActionPerformed

    private void btnZaduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduziActionPerformed
        int brojReda = listaZaposleni.getSelectedIndex();

        if (brojReda < 0) {
            JOptionPane.showMessageDialog(rootPane, "Morate odabrati zaposlenog iz liste svih radnika!", "Greška", JOptionPane.OK_OPTION);
            return;
        }

        ZaposleniDTO red = listaZaposleni.getSelectedValue();
        red.setUlogaRadnika(taUlogaRadnika.getText());

        ((DefaultListModel<ZaposleniDTO>) listaZaposleni.getModel()).removeElementAt(brojReda);

        DefaultListModel<ZaposleniDTO> mod = (DefaultListModel<ZaposleniDTO>) listaZaposleniZaduzeni.getModel();
        mod.addElement(red);

        taUlogaRadnika.setText("");
    }//GEN-LAST:event_btnZaduziActionPerformed

    private void listaZaposleniZaduzeniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaZaposleniZaduzeniValueChanged

    }//GEN-LAST:event_listaZaposleniZaduzeniValueChanged

    private void datumOtvaranjaNalogaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datumOtvaranjaNalogaFocusGained

    }//GEN-LAST:event_datumOtvaranjaNalogaFocusGained

    private void datumOtvaranjaNalogaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datumOtvaranjaNalogaFocusLost

    }//GEN-LAST:event_datumOtvaranjaNalogaFocusLost

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

   
    public void setNalog(RadniNalogDTO nalog) {
        this.nalog = nalog;
    }

    public void setIdVozila(int idVozila) {
        this.idVozila = idVozila;
    }

    public int getIdRadnogNaloga() {
        return idRadnogNaloga;
    }

    public int getIdVozila() {
        return idVozila;
    }

    public RadniNalogDTO getNalog() {
        return nalog;
    }
    
    public RadniNalogLogika getRadniNalogLogika() {
        return radniNalogLogika;
    }

    public JLabel getZaduzeni() {
        return Zaduzeni;
    }

    public JButton getBtnAzurirajNalog() {
        return btnAzurirajNalog;
    }

    public JButton getBtnDodajDio() {
        return btnDodajDio;
    }

    public JButton getBtnRazduzi() {
        return btnRazduzi;
    }

    public JButton getBtnUkloniDio() {
        return btnUkloniDio;
    }

    public JButton getBtnZaduzi() {
        return btnZaduzi;
    }

    public JCheckBox getCbPlaceno() {
        return cbPlaceno;
    }

    public JDateChooser getDatumOtvaranjaNaloga() {
        return datumOtvaranjaNaloga;
    }

    public JDateChooser getDatumZatvaranjaNaloga() {
        return datumZatvaranjaNaloga;
    }

    public JPanel getjPanel1() {
        return pnlOsnovni;
    }

    public JPanel getjPanel2() {
        return pnlPodosnovni;
    }

    public JScrollPane getjScrollPane1() {
        return spnlProblem;
    }

    public JScrollPane getjScrollPane2() {
        return spnlZaduzeni;
    }

    public JScrollPane getjScrollPane3() {
        return spnlRadnici;
    }

    public JScrollPane getjScrollPane4() {
        return spnlIzabraniDijelovi;
    }

    public JScrollPane getjScrollPane5() {
        return spnlLista;
    }

    public JScrollPane getjScrollPane6() {
        return spnlUloga;
    }

    public JList<ZaposleniDTO> getListaZaposleni() {
        return listaZaposleni;
    }

    public JList<ZaposleniDTO> getListaZaposleniZaduzeni() {
        return listaZaposleniZaduzeni;
    }

    public JDateChooser getPotrebnoZavrsitiDo() {
        return potrebnoZavrsitiDo;
    }

    public JSpinner getSpinnerKolicina() {
        return spinnerKolicina;
    }

    public JTextArea getTaProblem() {
        return taProblem;
    }

    public JTextArea getTaUlogaRadnika() {
        return taUlogaRadnika;
    }

    public JTable getTabelaDijelovi() {
        return tblDijelovi;
    }

    public JTable getTabelaIzabraniDijelovi() {
        return tblIzabraniDijelovi;
    }

    public JTextField getTfCijena() {
        return txtCijena;
    }

    public JTextField getTfCijenaDijela() {
        return txtCijenaDijela;
    }

    public JTextField getTfIdVozila() {
        return txtIdVozila;
    }

    public JTextField getTfKilometraza() {
        return txtKilometraza;
    }

    public JTextField getTfTroskovi() {
        return txtTroskovi;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmijeniRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmijeniRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmijeniRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmijeniRadniNalogDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmijeniRadniNalogDialog dialog = new IzmijeniRadniNalogDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Zaduzeni;
    private javax.swing.JButton btnAzurirajNalog;
    private javax.swing.JButton btnDodajDio;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnRazduzi;
    private javax.swing.JButton btnUkloniDio;
    private javax.swing.JButton btnZaduzi;
    private javax.swing.JCheckBox cbPlaceno;
    private com.toedter.calendar.JDateChooser datumOtvaranjaNaloga;
    private com.toedter.calendar.JDateChooser datumZatvaranjaNaloga;
    private javax.swing.JLabel lblCijena;
    private javax.swing.JLabel lblCijenaDijela;
    private javax.swing.JLabel lblIdVozila;
    private javax.swing.JLabel lblIzabraniDijelovi;
    private javax.swing.JLabel lblKilometraza;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblListaDijelova;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblOtvaranje;
    private javax.swing.JLabel lblSviRadnici;
    private javax.swing.JLabel lblTroskovi;
    private javax.swing.JLabel lblUloga;
    private javax.swing.JLabel lblZavrsetak;
    private javax.swing.JLabel lblZavrsiti;
    private javax.swing.JList<ZaposleniDTO> listaZaposleni;
    private javax.swing.JList<ZaposleniDTO> listaZaposleniZaduzeni;
    private javax.swing.JPanel pnlOsnovni;
    private javax.swing.JPanel pnlPodosnovni;
    private javax.swing.JPanel pnlPomocni1;
    private javax.swing.JPanel pnlPomocni2;
    private com.toedter.calendar.JDateChooser potrebnoZavrsitiDo;
    private javax.swing.JSpinner spinnerKolicina;
    private javax.swing.JScrollPane spnlIzabraniDijelovi;
    private javax.swing.JScrollPane spnlLista;
    private javax.swing.JScrollPane spnlProblem;
    private javax.swing.JScrollPane spnlRadnici;
    private javax.swing.JScrollPane spnlUloga;
    private javax.swing.JScrollPane spnlZaduzeni;
    private javax.swing.JTextArea taProblem;
    private javax.swing.JTextArea taUlogaRadnika;
    private javax.swing.JTable tblDijelovi;
    private javax.swing.JTable tblIzabraniDijelovi;
    private javax.swing.JTextField txtCijena;
    private javax.swing.JTextField txtCijenaDijela;
    private javax.swing.JTextField txtIdVozila;
    private javax.swing.JTextField txtKilometraza;
    private javax.swing.JTextField txtTroskovi;
    // End of variables declaration//GEN-END:variables
}
