/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoservismaric.dialog;

import data.dao.DAOFactory;
import data.dto.DioDTO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aco
 */
public class IzmijeniDioDialog extends javax.swing.JDialog {
       DefaultTableModel dtm;
    int red;

    /**
     * Creates new form IzmijeniDioDialog
     */
    public IzmijeniDioDialog(DefaultTableModel dtm, int red) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Ažuriranje dijelova");
        this.dtm = dtm;
        this.red = red;
        try {
            tfId.setText(((Integer) dtm.getValueAt(red, 0)).toString());
            tfSifra.setText((String) dtm.getValueAt(red, 1));
            tfNaziv.setText((String) dtm.getValueAt(red, 2));
            tfMarka.setText((String) dtm.getValueAt(red, 3));
            tfModel.setText((String) dtm.getValueAt(red, 4));
            tfGorivo.setText((String) dtm.getValueAt(red, 6));
            //Object d = (Object)dtm.getValueAt(red, 6);
            tfCijena.setText(((Object) dtm.getValueAt(red, 7)).toString());
            tfKolicina.setText(((Integer) dtm.getValueAt(red, 8)).toString());
            tfNovo.setText((String) dtm.getValueAt(red, 9));
            tfGodiste.setText(((Integer) dtm.getValueAt(red, 5)).toString());
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelzmijeniDio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tfNaziv = new javax.swing.JTextField();
        tfMarka = new javax.swing.JTextField();
        tfModel = new javax.swing.JTextField();
        tfGorivo = new javax.swing.JTextField();
        tfCijena = new javax.swing.JTextField();
        tfKolicina = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        btnAzuriraj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOdustani = new javax.swing.JButton();
        lbPoruka = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSifra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfNovo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tfGodiste = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelzmijeniDio.setBackground(new java.awt.Color(102, 153, 255));
        panelzmijeniDio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(476, 482));

        tfNaziv.setBackground(new java.awt.Color(102, 153, 255));
        tfNaziv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfNaziv.setForeground(new java.awt.Color(255, 255, 255));
        tfNaziv.setBorder(null);
        tfNaziv.setNextFocusableComponent(tfGorivo);

        tfMarka.setEditable(false);
        tfMarka.setBackground(new java.awt.Color(102, 153, 255));
        tfMarka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfMarka.setForeground(new java.awt.Color(255, 255, 255));
        tfMarka.setBorder(null);
        tfMarka.setNextFocusableComponent(tfModel);

        tfModel.setEditable(false);
        tfModel.setBackground(new java.awt.Color(102, 153, 255));
        tfModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfModel.setForeground(new java.awt.Color(255, 255, 255));
        tfModel.setBorder(null);
        tfModel.setNextFocusableComponent(tfGorivo);
        tfModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModelActionPerformed(evt);
            }
        });

        tfGorivo.setBackground(new java.awt.Color(102, 153, 255));
        tfGorivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfGorivo.setForeground(new java.awt.Color(255, 255, 255));
        tfGorivo.setBorder(null);
        tfGorivo.setNextFocusableComponent(tfCijena);
        tfGorivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGorivoActionPerformed(evt);
            }
        });

        tfCijena.setBackground(new java.awt.Color(102, 153, 255));
        tfCijena.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfCijena.setForeground(new java.awt.Color(255, 255, 255));
        tfCijena.setBorder(null);
        tfCijena.setNextFocusableComponent(tfKolicina);

        tfKolicina.setBackground(new java.awt.Color(102, 153, 255));
        tfKolicina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfKolicina.setForeground(new java.awt.Color(255, 255, 255));
        tfKolicina.setBorder(null);
        tfKolicina.setNextFocusableComponent(tfNovo);

        jLabel111.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setText("Naziv:");

        jLabel112.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jLabel112.setText("Marka:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Model:");

        jLabel113.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 255, 255));
        jLabel113.setText("Vrsta goriva:");

        jLabel115.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Cijena");

        jLabel114.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 255));
        jLabel114.setText("Količina:");

        btnAzuriraj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAzuriraj.setText("Ažuriraj");
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ažuriraj podatke o dijelu:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id:");

        btnOdustani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        lbPoruka.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPoruka.setText(" ");

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(102, 153, 255));
        tfId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfId.setForeground(new java.awt.Color(255, 255, 255));
        tfId.setBorder(null);
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Šifra:");

        tfSifra.setBackground(new java.awt.Color(102, 153, 255));
        tfSifra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfSifra.setForeground(new java.awt.Color(255, 255, 255));
        tfSifra.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(50, 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Novo:");

        tfNovo.setBackground(new java.awt.Color(102, 153, 255));
        tfNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfNovo.setForeground(new java.awt.Color(255, 255, 255));
        tfNovo.setBorder(null);
        tfNovo.setNextFocusableComponent(tfGodiste);

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setMinimumSize(new java.awt.Dimension(50, 5));
        jSeparator9.setPreferredSize(new java.awt.Dimension(50, 5));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Godište:");

        tfGodiste.setBackground(new java.awt.Color(102, 153, 255));
        tfGodiste.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfGodiste.setForeground(new java.awt.Color(255, 255, 255));
        tfGodiste.setBorder(null);

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator1)
                                .addComponent(tfNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(tfModel)
                                .addComponent(tfMarka)
                                .addComponent(tfId)
                                .addComponent(tfSifra, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator10)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(tfNovo)
                                .addComponent(tfGodiste))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbPoruka)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel115)
                            .addComponent(jLabel114))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addComponent(tfKolicina, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tfCijena)
                            .addComponent(tfGorivo)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111))
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112))
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGorivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel113, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel115))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel114))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPoruka)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tfNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel24))
                .addGap(0, 0, 0)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani)
                    .addComponent(btnAzuriraj))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelzmijeniDioLayout = new javax.swing.GroupLayout(panelzmijeniDio);
        panelzmijeniDio.setLayout(panelzmijeniDioLayout);
        panelzmijeniDioLayout.setHorizontalGroup(
            panelzmijeniDioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelzmijeniDioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelzmijeniDioLayout.setVerticalGroup(
            panelzmijeniDioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelzmijeniDioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelzmijeniDio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelzmijeniDio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfGorivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGorivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGorivoActionPerformed

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed
        String sifra = "";
        String naziv = "";
        Double cijena = null; 
        Integer godiste = null;
        boolean stanje = false; 
        String gorivo = "";
        String marka = "";
        String model = "";
        Integer kolicina = null;
        boolean flag = false;
        Integer id = null;
        
        //šifra
        sifra = tfSifra.getText();
        if(!"".equals(sifra)){
            DioDTO dioo = DAOFactory.getDAOFactory().getDioDAO().getDio(sifra);
            if(dioo.getId() != Integer.parseInt(tfId.getText())){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Šifra vec postoji!", "Greška", JOptionPane.ERROR_MESSAGE); 
                flag = true;
            }
            
        }else{
            JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(this, "Unesite šifru!", "Greška", JOptionPane.ERROR_MESSAGE);
            flag = true;
        }
        
        //naziv
        naziv = tfNaziv.getText();
        if("".equals(naziv)){
            JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(this, "Unesite naziv!", "Greška", JOptionPane.ERROR_MESSAGE);
            flag = true;
        }
        
        //id
        try{
            id = Integer.parseInt(tfId.getText());
        }catch(NumberFormatException e){
            if(!"".equals(tfId.getText())){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format cijene!", "Greška", JOptionPane.ERROR_MESSAGE);      
            }
        }
        
        //godiste
        try {
            godiste = Integer.parseInt(tfGodiste.getText());
        } catch (NumberFormatException e) {
            if (!"".equals(tfGodiste.getText())) {
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format godišta.", "Greška", JOptionPane.ERROR_MESSAGE);
                flag = true;
            }
            godiste = null;
        }
        if("Da".equals(tfNovo.getText())){
            stanje = true;
        }else if("Ne".equals(tfNovo.getText())){
            stanje = false;
        }else{
            JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(this, "Nepravilan format stanja, unesite 'Da' ili 'Ne'.", "Greška", JOptionPane.ERROR_MESSAGE);
            flag = true;
        }
        
        //vrsta gorivo
        gorivo = tfGorivo.getText(); 
        if(!"Svi".equals(gorivo) && !"Benzin".equals(gorivo) && !"Dizel".equals(gorivo)){
            JOptionPane jop = new JOptionPane();
            jop.showMessageDialog(this, "Nepravilan format vrste goriva, unesite 'Svi', 'Benzin' ili 'Dizel'.", "Greška", JOptionPane.ERROR_MESSAGE);
            flag = true;
        }
        //cijena
        try{
            cijena = Double.parseDouble(tfCijena.getText());
        }catch(NumberFormatException e){
            if(!"".equals(tfCijena.getText())){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format cijene!", "Greška", JOptionPane.ERROR_MESSAGE);      
            }else{
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Unesite cijenu!", "Greška", JOptionPane.ERROR_MESSAGE);
            }
            flag = true;
        }
        //kolicina
        try {
            kolicina = Integer.parseInt(tfKolicina.getText());
        } catch (NumberFormatException e) {
            if (!"".equals(tfKolicina.getText())) {
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format količine.", "Greška", JOptionPane.ERROR_MESSAGE);
                flag = true;
            }
            kolicina = null;
        }
        
        marka = tfMarka.getText();
        model = tfModel.getText();
        
        if(!flag){
        DioDTO dio = new DioDTO(id, sifra, naziv, gorivo, godiste, stanje, cijena, kolicina, true, marka, model);
        DAOFactory.getDAOFactory().getDioDAO().azurirajDio(dio);
        dtm.setValueAt(sifra, red, 1);
        dtm.setValueAt(naziv, red, 2);
        dtm.setValueAt(godiste, red, 5);
        dtm.setValueAt(gorivo, red, 6);
        dtm.setValueAt(cijena, red, 7);
        dtm.setValueAt(kolicina, red, 8);
        dtm.setValueAt(stanje == true ? "Da": "Ne", red, 9);
        JOptionPane jop = new JOptionPane();
        jop.showMessageDialog(this, "Uspješno ažuriran dio.", "Obavještenje", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        }
    }//GEN-LAST:event_btnAzurirajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModelActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbPoruka;
    private javax.swing.JPanel panelzmijeniDio;
    private javax.swing.JTextField tfCijena;
    private javax.swing.JTextField tfGodiste;
    private javax.swing.JTextField tfGorivo;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfKolicina;
    private javax.swing.JTextField tfMarka;
    private javax.swing.JTextField tfModel;
    private javax.swing.JTextField tfNaziv;
    private javax.swing.JTextField tfNovo;
    private javax.swing.JTextField tfSifra;
    // End of variables declaration//GEN-END:variables
}
