/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoservismaric.dialog;

import data.dao.DAOFactory;
import data.dto.DioDTO;
import data.dto.ProdanDioDTO;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aco
 */
public class ProdajDioDialog extends javax.swing.JDialog {
    DefaultTableModel dtm;
    int red;
    Double pdv;
    Double cijena = null;
    Integer kolicina = null;
    /**
     * Creates new form ProdajDioDialog
     */
    public ProdajDioDialog(DefaultTableModel dtm, int red, Double pdv, java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Prodaja dijelova");
        this.dtm = dtm;
        this.red = red;
        this.pdv = pdv;
        System.out.println("");
        jtfPDV.setText(String.format("%.2f", pdv));
        try {
            tfId.setText(((Integer) dtm.getValueAt(red, 0)).toString());
            tfSifra.setText((String) dtm.getValueAt(red, 1));
            tfNaziv.setText((String) dtm.getValueAt(red, 2));
            tfMarka.setText((String) dtm.getValueAt(red, 3));
            tfModel.setText((String) dtm.getValueAt(red, 4));
            tfGorivo.setText((String) dtm.getValueAt(red, 6));
            //Object d = (Object)dtm.getValueAt(red, 6);
            tfCijena.setText(((Object) dtm.getValueAt(red, 7)).toString());
            tfKolicina.setText(((Integer) dtm.getValueAt(red, 8)).toString());
            tfNovo.setText((String) dtm.getValueAt(red, 9));
            tfGodiste.setText(((Integer) dtm.getValueAt(red, 5)).toString());
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelzmijeniDio = new javax.swing.JPanel();
        pnlOsnovno = new javax.swing.JPanel();
        lblPodaciODijelu = new javax.swing.JLabel();
        pnlPodaciODijelu = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblMarka = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblNovo = new javax.swing.JLabel();
        lblGorivo = new javax.swing.JLabel();
        lblGodiste = new javax.swing.JLabel();
        lblCijena = new javax.swing.JLabel();
        lblKolicina = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lbPoruka = new javax.swing.JLabel();
        lblSifra = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfSifra = new javax.swing.JTextField();
        tfNaziv = new javax.swing.JTextField();
        tfMarka = new javax.swing.JTextField();
        tfModel = new javax.swing.JTextField();
        tfGorivo = new javax.swing.JTextField();
        tfCijena = new javax.swing.JTextField();
        tfKolicina = new javax.swing.JTextField();
        tfNovo = new javax.swing.JTextField();
        tfGodiste = new javax.swing.JTextField();
        pnlProdaja = new javax.swing.JPanel();
        lblCijenaProdaja = new javax.swing.JLabel();
        lblCijenaKol = new javax.swing.JLabel();
        lblPdv = new javax.swing.JLabel();
        btnOdustani = new javax.swing.JButton();
        btnProdaj = new javax.swing.JButton();
        jtfPDV = new javax.swing.JTextField();
        tfKolicinaProdaja = new javax.swing.JTextField();
        ttfCijenaProdaja = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        tfUkupno = new javax.swing.JTextField();
        btnUkupno = new javax.swing.JButton();
        lblPodaciProdaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelzmijeniDio.setBackground(new java.awt.Color(102, 153, 255));
        panelzmijeniDio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelzmijeniDio.setNextFocusableComponent(ttfCijenaProdaja);

        pnlOsnovno.setBackground(new java.awt.Color(102, 153, 255));
        pnlOsnovno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlOsnovno.setPreferredSize(new java.awt.Dimension(476, 482));

        lblPodaciODijelu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPodaciODijelu.setForeground(new java.awt.Color(255, 255, 255));
        lblPodaciODijelu.setText("Podaci o dijelu:");

        pnlPodaciODijelu.setBackground(new java.awt.Color(102, 153, 255));
        pnlPodaciODijelu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlPodaciODijelu.setEnabled(false);

        lblNaziv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNaziv.setForeground(new java.awt.Color(255, 255, 255));
        lblNaziv.setText("Naziv:");

        lblMarka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarka.setForeground(new java.awt.Color(255, 255, 255));
        lblMarka.setText("Marka:");

        lblModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("Model:");

        lblNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNovo.setForeground(new java.awt.Color(255, 255, 255));
        lblNovo.setText("Novo:");

        lblGorivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGorivo.setForeground(new java.awt.Color(255, 255, 255));
        lblGorivo.setText("Vrsta goriva:");

        lblGodiste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGodiste.setForeground(new java.awt.Color(255, 255, 255));
        lblGodiste.setText("Godište:");

        lblCijena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCijena.setForeground(new java.awt.Color(255, 255, 255));
        lblCijena.setText("Cijena");

        lblKolicina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKolicina.setForeground(new java.awt.Color(255, 255, 255));
        lblKolicina.setText("Količina:");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Id:");

        lbPoruka.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPoruka.setText(" ");

        lblSifra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSifra.setForeground(new java.awt.Color(255, 255, 255));
        lblSifra.setText("Šifra:");

        tfId.setEditable(false);

        tfSifra.setEditable(false);
        tfSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSifraActionPerformed(evt);
            }
        });

        tfNaziv.setEditable(false);

        tfMarka.setEditable(false);

        tfModel.setEditable(false);

        tfGorivo.setEditable(false);

        tfCijena.setEditable(false);

        tfKolicina.setEditable(false);

        tfNovo.setEditable(false);

        tfGodiste.setEditable(false);

        javax.swing.GroupLayout pnlPodaciODijeluLayout = new javax.swing.GroupLayout(pnlPodaciODijelu);
        pnlPodaciODijelu.setLayout(pnlPodaciODijeluLayout);
        pnlPodaciODijeluLayout.setHorizontalGroup(
            pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciODijeluLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPodaciODijeluLayout.createSequentialGroup()
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMarka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfSifra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNaziv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfModel)
                            .addComponent(tfMarka, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfId)
                            .addGroup(pnlPodaciODijeluLayout.createSequentialGroup()
                                .addComponent(tfGorivo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addGap(1, 1, 1))))
                    .addGroup(pnlPodaciODijeluLayout.createSequentialGroup()
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblGorivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCijena)
                                .addComponent(lblKolicina)))
                        .addGap(40, 40, 40)
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfNovo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKolicina, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCijena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGodiste, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addComponent(lbPoruka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPodaciODijeluLayout.setVerticalGroup(
            pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPodaciODijeluLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifra)
                    .addComponent(tfSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(tfNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarka)
                    .addComponent(tfMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodaciODijeluLayout.createSequentialGroup()
                        .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGorivo)
                            .addComponent(tfGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCijena)
                            .addComponent(tfCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPodaciODijeluLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblKolicina)
                                .addGap(0, 0, 0)
                                .addComponent(lbPoruka))
                            .addGroup(pnlPodaciODijeluLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(tfKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNovo)
                                    .addComponent(tfNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblModel))
                .addGap(7, 7, 7)
                .addGroup(pnlPodaciODijeluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGodiste)
                    .addComponent(tfGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlPodaciODijeluLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfId, tfSifra});

        pnlProdaja.setBackground(new java.awt.Color(102, 153, 255));
        pnlProdaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblCijenaProdaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCijenaProdaja.setForeground(new java.awt.Color(255, 255, 255));
        lblCijenaProdaja.setText("Cijena:");

        lblCijenaKol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCijenaKol.setForeground(new java.awt.Color(240, 240, 240));
        lblCijenaKol.setText("Količina:");

        lblPdv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPdv.setForeground(new java.awt.Color(240, 240, 240));
        lblPdv.setText("Vrijednost PDV-a:");

        btnOdustani.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOdustani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/cancel (1).png"))); // NOI18N
        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        btnProdaj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProdaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoservismaric/images/shop-cart.png"))); // NOI18N
        btnProdaj.setText("Prodaj");
        btnProdaj.setIconTextGap(10);
        btnProdaj.setNextFocusableComponent(btnOdustani);
        btnProdaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdajActionPerformed(evt);
            }
        });

        jtfPDV.setNextFocusableComponent(btnUkupno);

        tfKolicinaProdaja.setNextFocusableComponent(jtfPDV);

        ttfCijenaProdaja.setNextFocusableComponent(tfKolicinaProdaja);

        tfUkupno.setEditable(false);

        btnUkupno.setText("Izračunaj ukupno:");
        btnUkupno.setNextFocusableComponent(btnProdaj);
        btnUkupno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkupnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdajaLayout = new javax.swing.GroupLayout(pnlProdaja);
        pnlProdaja.setLayout(pnlProdajaLayout);
        pnlProdajaLayout.setHorizontalGroup(
            pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProdajaLayout.createSequentialGroup()
                        .addComponent(jSeparator11)
                        .addContainerGap())
                    .addGroup(pnlProdajaLayout.createSequentialGroup()
                        .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPdv)
                            .addComponent(lblCijenaKol)
                            .addComponent(lblCijenaProdaja))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfKolicinaProdaja, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(ttfCijenaProdaja, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jtfPDV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdajaLayout.createSequentialGroup()
                        .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUkupno)
                            .addComponent(btnOdustani))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnProdaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfUkupno, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        pnlProdajaLayout.setVerticalGroup(
            pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdajaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCijenaProdaja)
                    .addComponent(ttfCijenaProdaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCijenaKol)
                    .addComponent(tfKolicinaProdaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPdv)
                    .addComponent(jtfPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUkupno))
                .addGap(27, 27, 27)
                .addGroup(pnlProdajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdaj))
                .addGap(27, 27, 27))
        );

        tfUkupno.getAccessibleContext().setAccessibleDescription("");

        lblPodaciProdaja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPodaciProdaja.setForeground(new java.awt.Color(255, 255, 255));
        lblPodaciProdaja.setText("Podaci za prodaju:");

        javax.swing.GroupLayout pnlOsnovnoLayout = new javax.swing.GroupLayout(pnlOsnovno);
        pnlOsnovno.setLayout(pnlOsnovnoLayout);
        pnlOsnovnoLayout.setHorizontalGroup(
            pnlOsnovnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOsnovnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOsnovnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPodaciODijelu)
                    .addComponent(pnlPodaciODijelu, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOsnovnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOsnovnoLayout.createSequentialGroup()
                        .addComponent(lblPodaciProdaja)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlProdaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOsnovnoLayout.setVerticalGroup(
            pnlOsnovnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOsnovnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOsnovnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPodaciODijelu)
                    .addComponent(lblPodaciProdaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOsnovnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlProdaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPodaciODijelu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelzmijeniDioLayout = new javax.swing.GroupLayout(panelzmijeniDio);
        panelzmijeniDio.setLayout(panelzmijeniDioLayout);
        panelzmijeniDioLayout.setHorizontalGroup(
            panelzmijeniDioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelzmijeniDioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOsnovno, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelzmijeniDioLayout.setVerticalGroup(
            panelzmijeniDioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelzmijeniDioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOsnovno, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelzmijeniDio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelzmijeniDio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdajActionPerformed
       
       boolean flag = false;
       Integer kolNaStanju = (Integer) dtm.getValueAt(red, 8);
       
       try {
            kolicina = Integer.parseInt(tfKolicinaProdaja.getText());
            if(kolicina > kolNaStanju || kolicina < 0){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Na stanju imate "+kolNaStanju + ", a želite da prodate "+kolicina,
                        "Greška", JOptionPane.ERROR_MESSAGE);
                flag = true;
                kolicina = null;
            }                
        } catch (NumberFormatException e) {
            if (!"".equals(tfKolicinaProdaja.getText())) {
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format količine.", "Greška", JOptionPane.ERROR_MESSAGE);
                flag = true;
            }
            kolicina = null;
        }
       
       try{
            cijena = Double.parseDouble(ttfCijenaProdaja.getText());
        }catch(NumberFormatException e){
            if(!"".equals(ttfCijenaProdaja.getText())){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format cijene!", "Greška", JOptionPane.ERROR_MESSAGE);      
            }else{
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Unesite cijenu!", "Greška", JOptionPane.ERROR_MESSAGE);
            }
            flag = true;
            cijena = null;
        }
       if(!flag){
           Date datum = new Date(System.currentTimeMillis());
           System.out.println("datum " +datum);
           ProdanDioDTO dio = new ProdanDioDTO((Integer)dtm.getValueAt(red, 0), cijena, kolicina, datum);
           DAOFactory.getDAOFactory().getProdanDioDAO().dodajProdanDio(dio);
           DioDTO prodajniDio = DAOFactory.getDAOFactory().getDioDAO().getDio((Integer)dtm.getValueAt(red, 0));
           prodajniDio.setKolicina(prodajniDio.getKolicina() - kolicina);
           DAOFactory.getDAOFactory().getDioDAO().azurirajDio(prodajniDio);
           dtm.setValueAt(prodajniDio.getKolicina(), red, 8);
           JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Uspješno ste prodali dio", "Obavještenje", JOptionPane.INFORMATION_MESSAGE);
                dispose();
       }
    }//GEN-LAST:event_btnProdajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnUkupnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkupnoActionPerformed
        boolean flag = false;
       Integer kolNaStanju = (Integer) dtm.getValueAt(red, 8);
       
       try {
            kolicina = Integer.parseInt(tfKolicinaProdaja.getText());
            if(kolicina > kolNaStanju || kolicina < 0){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Na stanju imate "+kolNaStanju + ", a želite da prodate "+kolicina,
                        "Greška", JOptionPane.ERROR_MESSAGE);
                flag = true;
                kolicina = null;
            }                
        } catch (NumberFormatException e) {
            if (!"".equals(tfKolicinaProdaja.getText())) {
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format količine.", "Greška", JOptionPane.ERROR_MESSAGE);
                flag = true;
            }
            kolicina = null;
        }
       
       try{
            cijena = Double.parseDouble(ttfCijenaProdaja.getText());
        }catch(NumberFormatException e){
            if(!"".equals(ttfCijenaProdaja.getText())){
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Nepravilan format cijene, primjer(33.32)!", "Greška", JOptionPane.ERROR_MESSAGE);      
            }else{
                JOptionPane jop = new JOptionPane();
                jop.showMessageDialog(this, "Unesite cijenu!", "Greška", JOptionPane.ERROR_MESSAGE);
            }
            flag = true;
            cijena = null;
        }
        if(cijena != null && kolicina != null){
             Double rez = (cijena + pdv*cijena/100)* kolicina;
            tfUkupno.setText(String.format("%.2f", rez));
        }else{
            tfUkupno.setText("0");
        }
    }//GEN-LAST:event_btnUkupnoActionPerformed

    private void tfSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSifraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnProdaj;
    private javax.swing.JButton btnUkupno;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JTextField jtfPDV;
    private javax.swing.JLabel lbPoruka;
    private javax.swing.JLabel lblCijena;
    private javax.swing.JLabel lblCijenaKol;
    private javax.swing.JLabel lblCijenaProdaja;
    private javax.swing.JLabel lblGodiste;
    private javax.swing.JLabel lblGorivo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblKolicina;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblNovo;
    private javax.swing.JLabel lblPdv;
    private javax.swing.JLabel lblPodaciODijelu;
    private javax.swing.JLabel lblPodaciProdaja;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JPanel panelzmijeniDio;
    private javax.swing.JPanel pnlOsnovno;
    private javax.swing.JPanel pnlPodaciODijelu;
    private javax.swing.JPanel pnlProdaja;
    private javax.swing.JTextField tfCijena;
    private javax.swing.JTextField tfGodiste;
    private javax.swing.JTextField tfGorivo;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfKolicina;
    private javax.swing.JTextField tfKolicinaProdaja;
    private javax.swing.JTextField tfMarka;
    private javax.swing.JTextField tfModel;
    private javax.swing.JTextField tfNaziv;
    private javax.swing.JTextField tfNovo;
    private javax.swing.JTextField tfSifra;
    private javax.swing.JTextField tfUkupno;
    private javax.swing.JTextField ttfCijenaProdaja;
    // End of variables declaration//GEN-END:variables
}
