/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoservismaric.dialog;

import com.sun.glass.events.KeyEvent;
import data.dao.DAOFactory;
import data.dto.ModelVozilaDTO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DulleX
 */
public class IzmijeniIzbrisiModelDialog extends javax.swing.JDialog {

    /**
     * Creates new form IzmijeniIzbrisiModelDialog
     */
    
    ArrayList<ModelVozilaDTO> modeli =null;
    String marka;
    String model;
    
    public IzmijeniIzbrisiModelDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        modeli = DAOFactory.getDAOFactory().getModelVozilaDAO().sviModeli();
         DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        for(ModelVozilaDTO m: modeli){
            Object[] objekat = {m.getMarka(), m.getModel()};
            model.addRow(objekat);
        }
        
        tabela.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfMarka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfModel = new javax.swing.JTextField();
        tfMarkaAzuriraj = new javax.swing.JTextField();
        tfModelAzuriraj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAzuriraj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbPoruka = new javax.swing.JLabel();
        btnIzmijeni = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmijeni/Izbrisi model");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Model:");

        tfMarka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMarkaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMarkaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marka:");

        tfModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModelActionPerformed(evt);
            }
        });
        tfModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfModelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfModelKeyTyped(evt);
            }
        });

        tfMarkaAzuriraj.setEditable(false);

        tfModelAzuriraj.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Marka:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Model:");

        btnAzuriraj.setText("Azuriraj");
        btnAzuriraj.setEnabled(false);
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.setEnabled(false);
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marka", "Model"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        lbPoruka.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbPoruka)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnOdustani)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAzuriraj))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(5, 5, 5)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfModelAzuriraj, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(tfMarkaAzuriraj))))
                        .addGap(43, 43, 43))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfMarka, tfModel});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMarkaAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfModelAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAzuriraj)
                            .addComponent(btnOdustani)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPoruka)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfMarka, tfModel});

        btnIzmijeni.setText("Izmijeni");
        btnIzmijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmijeniActionPerformed(evt);
            }
        });

        btnIzbrisi.setText("Izbrisi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnIzmijeni)
                .addGap(18, 18, 18)
                .addComponent(btnIzbrisi)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmijeni)
                    .addComponent(btnIzbrisi))
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfMarkaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMarkaKeyPressed
        
    }//GEN-LAST:event_tfMarkaKeyPressed

    private void tfMarkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMarkaKeyTyped
        String marka = tfMarka.getText();
        String mod = tfModel.getText();
        
        
        if((evt.getKeyChar() >= KeyEvent.VK_0 && evt.getKeyChar() <= KeyEvent.VK_9) || (evt.getKeyChar() > 64 && evt.getKeyChar() < 91) || (evt.getKeyChar() > 96 && evt.getKeyChar() < 123) || evt.getKeyChar() == 8){
                   
            Object[] kolone = {"Marka", "Model"};
            DefaultTableModel model = new DefaultTableModel(kolone, 0);
        for(ModelVozilaDTO m : modeli){
            //System.out.println(m.getMarka().toLowerCase() + marka.toLowerCase());
            if((mod == null || "".equals(mod)) && m.getMarka().toLowerCase().startsWith(marka.toLowerCase())){
                Object[] rowData = {m.getMarka(), m.getModel()};
                model.addRow(rowData);
                System.out.println(m.getMarka().toLowerCase() + " DDD " + marka.toLowerCase());
            }
            else if((marka == null || "".equals(marka)) && m.getModel().toLowerCase().startsWith(mod.toLowerCase())){
                Object[] rowData = {m.getMarka(), m.getModel()};
                model.addRow(rowData);
            }
            else{
                if(m.getMarka().toLowerCase().startsWith(marka.toLowerCase()) && m.getModel().toLowerCase().startsWith(mod.toLowerCase())){
                    Object[] rowData = {m.getMarka(), m.getModel()};
                    model.addRow(rowData);
                }
            }
        }
        
        tabela.setModel(model);
        
        }
        
        
    }//GEN-LAST:event_tfMarkaKeyTyped

    private void btnIzmijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmijeniActionPerformed
        int column = 0;
        int row = tabela.getSelectedRow();
        if(row != -1){
            String marka = tabela.getModel().getValueAt(row, 0).toString();
            String model = tabela.getModel().getValueAt(row, 1).toString();
            this.marka = marka;
            this.model = model;
            tfMarkaAzuriraj.setText(marka);
            tfModelAzuriraj.setText(model);
            tfMarkaAzuriraj.setEditable(true);
            tfModelAzuriraj.setEditable(true);
            btnOdustani.setEnabled(true);
            btnAzuriraj.setEnabled(true);
            
            tabela.setEnabled(false);
            tfMarka.setEditable(false);
            tfModel.setEditable(false);
            tfMarka.setText("");
            tfModel.setText("");
            tfMarka.setBackground(Color.gray);
            tfModel.setBackground(Color.gray);
            btnIzmijeni.setEnabled(false);
            btnIzbrisi.setEnabled(false);
        }
        else{
            lbPoruka.setText("Morate izabrati red u tabeli.");
            lbPoruka.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnIzmijeniActionPerformed

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed
        String marka = tfMarkaAzuriraj.getText();
        String model = tfModelAzuriraj.getText();
        
        ModelVozilaDTO m = DAOFactory.getDAOFactory().getModelVozilaDAO().model(this.marka, this.model);
        m.setMarka(marka);
        m.setModel(model);
        if(DAOFactory.getDAOFactory().getModelVozilaDAO().azurirajModel(m)){
            lbPoruka.setText("Uspjesno!");
            lbPoruka.setForeground(Color.green);
        }
        else{
            lbPoruka.setText("Neuspjesno!");
            lbPoruka.setForeground(Color.red);
        }
        
       this.modeli = DAOFactory.getDAOFactory().getModelVozilaDAO().sviModeli();
       Object[] columns = {"Marka", "Model"};
       DefaultTableModel dtm = new DefaultTableModel(columns,0);
       for(ModelVozilaDTO mmmm : this.modeli){
           Object[] row = {mmmm.getMarka(), mmmm.getModel()};
           dtm.addRow(row);
       }
       tabela.setModel(dtm);
       
       tfMarkaAzuriraj.setEditable(false);
        tfModelAzuriraj.setEditable(false);
        tfMarkaAzuriraj.setText("");
        tfModelAzuriraj.setText("");
        tfMarkaAzuriraj.setBackground(Color.gray);
        tfModelAzuriraj.setBackground(Color.gray);
        btnOdustani.setEnabled(false);
        btnAzuriraj.setEnabled(false);
        tabela.setEnabled(true);
        btnIzmijeni.setEnabled(true);
        btnIzbrisi.setEnabled(true);
        
        tfMarka.setEditable(true);
        tfModel.setEditable(true);
        tfMarka.setBackground(Color.white);
        tfModel.setBackground(Color.white);
        tfMarka.setText("");
        tfModel.setText("");
       
    }//GEN-LAST:event_btnAzurirajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        tabela.setEnabled(true);
        tfMarkaAzuriraj.setEditable(false);
        tfModelAzuriraj.setEditable(false);
        tfMarkaAzuriraj.setText("");
        tfModelAzuriraj.setText("");
        tfMarkaAzuriraj.setBackground(Color.gray);
        tfModelAzuriraj.setBackground(Color.gray);
        btnOdustani.setEnabled(false);
        btnAzuriraj.setEnabled(false);
        btnIzmijeni.setEnabled(true);
        btnIzbrisi.setEnabled(true);
        
        tfMarka.setEditable(true);
        tfModel.setEditable(true);
        tfMarka.setBackground(Color.white);
        tfModel.setBackground(Color.white);
        tfMarka.setText("");
        tfModel.setText("");
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void tfModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModelActionPerformed
        
    }//GEN-LAST:event_tfModelActionPerformed

    private void tfModelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModelKeyTyped
         String marka = tfMarka.getText();
        String mod = tfModel.getText();
        
        
        if((evt.getKeyChar() >= KeyEvent.VK_0 && evt.getKeyChar() <= KeyEvent.VK_9) || (evt.getKeyChar() > 64 && evt.getKeyChar() < 91) || (evt.getKeyChar() > 96 && evt.getKeyChar() < 123) || evt.getKeyChar() == 8){
                
            System.out.println("DAAA");
            Object[] kolone = {"Marka", "Model"};
            DefaultTableModel model = new DefaultTableModel(kolone, 0);
        for(ModelVozilaDTO m : modeli){
            //System.out.println(m.getMarka().toLowerCase() + marka.toLowerCase());
            if((mod == null || "".equals(mod)) && m.getMarka().toLowerCase().startsWith(marka.toLowerCase())){
                Object[] rowData = {m.getMarka(), m.getModel()};
                model.addRow(rowData);
            }
            else if((marka == null || "".equals(marka)) && m.getModel().toLowerCase().startsWith(mod.toLowerCase())){
                Object[] rowData = {m.getMarka(), m.getModel()};
                model.addRow(rowData);
            }
            else{
                if(m.getMarka().toLowerCase().startsWith(marka.toLowerCase()) && m.getModel().toLowerCase().startsWith(mod.toLowerCase())){
                    Object[] rowData = {m.getMarka(), m.getModel()};
                    model.addRow(rowData);
                }
            }
        }
        
        tabela.setModel(model);
        
        }

    }//GEN-LAST:event_tfModelKeyTyped

    private void tfModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfModelKeyPressed
      
    }//GEN-LAST:event_tfModelKeyPressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmijeniIzbrisiModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmijeniIzbrisiModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmijeniIzbrisiModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmijeniIzbrisiModelDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmijeniIzbrisiModelDialog dialog = new IzmijeniIzbrisiModelDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmijeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPoruka;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfMarka;
    private javax.swing.JTextField tfMarkaAzuriraj;
    private javax.swing.JTextField tfModel;
    private javax.swing.JTextField tfModelAzuriraj;
    // End of variables declaration//GEN-END:variables
}
